# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/socsemvar',
                'doc_host': 'https://wuqui.github.io',
                'git_url': 'https://github.com/wuqui/socsemvar',
                'lib_path': 'socsemvar'},
  'syms': {'socsemvar.core': {'socsemvar.core.foo': ('core.html#foo', 'socsemvar/core.py')}}}
