# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/socsemvar',
                'doc_host': 'https://wuqui.github.io',
                'git_url': 'https://github.com/wuqui/socsemvar',
                'lib_path': 'socsemvar'},
  'syms': { 'socsemvar.core': {'socsemvar.core.foo': ('core.html#foo', 'socsemvar/core.py')},
            'socsemvar.read_data': { 'socsemvar.read_data.get_fpaths_subreddit': ( 'read_data.html#get_fpaths_subreddit',
                                                                                   'socsemvar/read_data.py'),
                                     'socsemvar.read_data.get_fpaths_year': ('read_data.html#get_fpaths_year', 'socsemvar/read_data.py'),
                                     'socsemvar.read_data.read_multi_comments_csvs': ( 'read_data.html#read_multi_comments_csvs',
                                                                                       'socsemvar/read_data.py'),
                                     'socsemvar.read_data.read_one_comments_csv': ( 'read_data.html#read_one_comments_csv',
                                                                                    'socsemvar/read_data.py')}}}
