# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_semantic-change.ipynb.

# %% auto 0
__all__ = ['get_fpaths_year', 'get_fpaths_subreddit']

# %% ../nbs/01_semantic-change.ipynb 3
from pathlib import Path
import pandas as pd

# %% ../nbs/01_semantic-change.ipynb 9
def get_fpaths_year(year: str, dir='../data_test/years'): 
	dir_path = Path(dir)
	return list(dir_path.glob(f'{year}*.csv'))

# %% ../nbs/01_semantic-change.ipynb 11
def get_fpaths_subreddit(subreddit: str, dir='../data_test/subreddits'): 
	dir_path = Path(dir)
	return list(dir_path.glob(f'{subreddit}*.csv'))
